name: Release

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: hacs validation
      uses: "hacs/action@main"
      with:
        category: "plugin"
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/*.js
    - name: release
      if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request'
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require('fs').promises;
          const path = require('path');
          console.log('environment', process.versions);

          const { repo: { owner, repo }, sha, ref } = context;
          console.log({ owner, repo, sha, ref });

          const name = ref.replace('refs/tags/', '');
          const release = await github.repos.createRelease({
            owner, repo, name,
            tag_name: name,
            draft: true,
            target_commitish: sha
          });

          console.log('created release', { release });
          const file = './dist/combined-card.js';
          console.log('uploading', file);

          await github.repos.uploadReleaseAsset({
            owner, repo,
            release_id: release.data.id,
            name: path.basename(file),
            data: await fs.readFile(`./${file}`)
          });

